// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4UUqon-BDUgXCfvmSuQ4Qf7gx16fX9V8',
    appId: '1:834985273311:web:c7cf123ce9247281ce066a',
    messagingSenderId: '834985273311',
    projectId: 'loginregistration-a6867',
    authDomain: 'loginregistration-a6867.firebaseapp.com',
    storageBucket: 'loginregistration-a6867.appspot.com',
    measurementId: 'G-4ZVNQPNZ99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1dECSuIpr-vlBkEL3Wgn5_8Q71QcnAfk',
    appId: '1:834985273311:android:aa48038e275292d0ce066a',
    messagingSenderId: '834985273311',
    projectId: 'loginregistration-a6867',
    storageBucket: 'loginregistration-a6867.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNfglp41ThXTK8tIC7x0jkBH1-MkErEzg',
    appId: '1:834985273311:ios:cf159f35f73aa319ce066a',
    messagingSenderId: '834985273311',
    projectId: 'loginregistration-a6867',
    storageBucket: 'loginregistration-a6867.appspot.com',
    iosClientId: '834985273311-occegniulo88qndpoh1hdegqk6hq2h84.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNfglp41ThXTK8tIC7x0jkBH1-MkErEzg',
    appId: '1:834985273311:ios:cf159f35f73aa319ce066a',
    messagingSenderId: '834985273311',
    projectId: 'loginregistration-a6867',
    storageBucket: 'loginregistration-a6867.appspot.com',
    iosClientId: '834985273311-occegniulo88qndpoh1hdegqk6hq2h84.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
